name: Build JMSML Executables

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet Packages
      run: nuget restore source/JointMilitarySymbologyLibraryCS/JointMilitarySymbologyLibrary.sln

    - name: Build Core Library (DLL)
      run: msbuild source/JointMilitarySymbologyLibraryCS/JointMilitarySymbologyLibrary.csproj /p:Configuration=Release

    - name: Build Windows GUI Demo (Test.exe)
      run: msbuild source/JointMilitarySymbologyLibraryCS/Test/JMSML_Demo.csproj /p:Configuration=Release

    - name: Build Command Line Tool (jmsml.exe)
      run: msbuild source/JointMilitarySymbologyLibraryCS/jmsml/jmsml.csproj /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Executables
        path: |
          source/JointMilitarySymbologyLibraryCS/Test/bin/Release/
          source/JointMilitarySymbologyLibraryCS/jmsml/bin/Release/
